insert into public.upgrade_cards (
  domain,
  level,
  basic_phrase,
  pro_phrase,
  upgrade_label,
  context_dialogue_1,
  context_dialogue_2,
  when_to_use,
  when_not_to_use,
  register,
  published_at
)
values
  (
    'professional',
    'intermediate',
    'I''m very busy.',
    'I''m swamped.',
    'Basic → Professional',
    '{"label":"At work","lines":["Manager: Can you join the 3 PM call?","You: I''m swamped right now, but I''ll make it work."]}',
    '{"label":"With a friend","lines":["Friend: Want to grab lunch?","You: I''d love to, but I''m swamped this week."]}',
    'Use it in conversation when you have a lot to do and want to sound natural.',
    'Avoid it in very formal written communication.',
    'casual',
    current_date - 9
  ),
  (
    'professional',
    'intermediate',
    'Let''s start.',
    'Let''s get the ball rolling.',
    'Basic → Professional',
    '{"label":"In a meeting","lines":["You: Alright everyone, let''s get the ball rolling."]}',
    '{"label":"On a project","lines":["You: We''ve planned enough. Let''s get the ball rolling."]}',
    'Use it to begin a meeting, project, or activity with energy.',
    'Avoid it in very formal written documents.',
    'neutral',
    current_date - 8
  ),
  (
    'professional',
    'intermediate',
    'I forgot.',
    'It slipped my mind.',
    'Basic → Natural',
    '{"label":"At work","lines":["Manager: Did you send the report?","You: It slipped my mind. I''ll send it now."]}',
    '{"label":"With a friend","lines":["Friend: You didn''t call me back.","You: I''m sorry, it slipped my mind."]}',
    'Use it for a small, honest mistake when you want to sound natural.',
    'Do not overuse it, because repeated use can sound irresponsible.',
    'neutral',
    current_date - 7
  ),
  (
    'social',
    'beginner',
    'How are you?',
    'How have you been?',
    'Basic → Natural',
    '{"label":"With a colleague","lines":["You: Hey, how have you been?"]}',
    '{"label":"With an old friend","lines":["You: It''s been ages. How have you been?"]}',
    'Use it with someone you have not seen recently.',
    'Do not use it when meeting someone for the first time.',
    'casual',
    current_date - 6
  ),
  (
    'interview',
    'intermediate',
    'I don''t want to.',
    'I''d rather not.',
    'Basic → Professional',
    '{"label":"In an interview","lines":["Interviewer: Would you relocate?","You: I''d rather not relocate, but I''m flexible about remote work."]}',
    '{"label":"With a manager","lines":["Manager: Can you work this weekend?","You: I''d rather not, but I can help if it''s urgent."]}',
    'Use it as a softer, professional way to decline.',
    'Follow it with a reason or an alternative.',
    'formal',
    current_date - 5
  ),
  (
    'grammar_fix',
    'beginner',
    'I seen that movie.',
    'I have seen that movie.',
    'Wrong → Correct',
    '{"label":"With a friend","lines":["Friend: Have you watched it?","You: Yes, I have seen it three times."]}',
    '{"label":"At work","lines":["Colleague: Did you watch the presentation?","You: Yes, I have seen it."]}',
    'Use “have seen” for past experience connected to the present.',
    'Never use “I seen” without an auxiliary verb.',
    'neutral',
    current_date - 4
  ),
  (
    'smart_replies',
    'beginner',
    'Yes.',
    'Absolutely.',
    'Basic → Confident',
    '{"label":"At work","lines":["Manager: Are you ready to present?","You: Absolutely. I''ve prepared thoroughly."]}',
    '{"label":"With a friend","lines":["Friend: Are you coming tonight?","You: Absolutely!"]}',
    'Use it to sound enthusiastic and confident.',
    'Do not use it for every yes, or it can sound exaggerated.',
    'casual',
    current_date - 3
  ),
  (
    'professional',
    'advanced',
    'He is very smart.',
    'He is sharp.',
    'Basic → Advanced',
    '{"label":"Recommending a colleague","lines":["You: You should meet David. He''s incredibly sharp."]}',
    '{"label":"Describing a teammate","lines":["You: She''s sharp. She spotted the issue immediately."]}',
    'Use it to describe someone as quick-thinking and capable.',
    'Use more formal language in an official reference letter.',
    'neutral',
    current_date - 2
  ),
  (
    'professional',
    'beginner',
    'I don''t care.',
    'It doesn''t matter to me.',
    'Basic → Polite',
    '{"label":"At work","lines":["Manager: Morning or afternoon?","You: Either works. It doesn''t matter to me."]}',
    '{"label":"With a friend","lines":["Friend: Coffee or tea?","You: It doesn''t matter to me."]}',
    'Use it to express that either option is acceptable.',
    'Avoid “I don''t care” at work because it can sound dismissive.',
    'neutral',
    current_date - 1
  ),
  (
    'social',
    'intermediate',
    'I am very happy.',
    'I''m over the moon.',
    'Basic → Expressive',
    '{"label":"Sharing good news","lines":["You: I got promoted. I''m over the moon!"]}',
    '{"label":"Celebrating a friend","lines":["You: I''m over the moon for you!"]}',
    'Use it for genuinely exciting news or strong happiness.',
    'Do not use it for small, ordinary pleasures.',
    'casual',
    current_date
  );
